# Generated by Django 5.2.5 on 2025-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLFSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('employment_rate', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='api_plfsrec_state_54f056_idx'), models.Index(fields=['gender'], name='api_plfsrec_gender_e7a656_idx'), models.Index(fields=['year'], name='api_plfsrec_year_9dfc29_idx')],
            },
        ),
    ]
